kind: Deployment
apiVersion: apps/v1
metadata:
  name: riverconsulting-deployment
  labels:
    app: riverconsulting
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: riverconsulting
  template:
    metadata:
      labels:
        app: riverconsulting
    spec:
      containers:
      - name: riverconsulting
        image: karthequian/helloworld:latest
        ports:
        - containerPort: 80
        resources:
         limits:
          memory: "128Mi"
          cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: riverconsulting-service
  labels:
    app: riverconsulting-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: riverconsulting
  ports:
  - name: riverconsulting-port
    protocol: TCP
    port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
    
  name: riverconsulting-nginx
  namespace: dev
spec:
  tls:
  - hosts:
    - dev-riverconsulting.westeurope.cloudapp.azure.com
    secretName: test-staging-letsencrypt
  rules:
    - host: dev-riverconsulting.westeurope.cloudapp.azure.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
              service:
                name: riverconsulting-service
                port: 
                  number: 80